### ISSUE TITLE
[nodemon] failed to start process, "ts-node" exec not found

### ISSUE THREAD

**Issue by Raidus** [joelgriffith/browserless#1]
Hi,

the docker version is working properly but if I try to `npm run dev` I'll get following error:

`[nodemon] failed to start process, "ts-node" exec not found`

What it's working in my case:

1. changing port to `8081` in src/config.ts
2. `npm run build`
3. `npm run start`

**Comment by JackZhang1988** [comment]
you should install ```ts-node``` first, run ```npm install -g ts-node```

**Comment by joelgriffith** [comment]
Just added it to devDeps and pushed on `master`. Shouldn't need to install it globally now
