### ISSUE TITLE
Problem with docker run option --shm-size=1gb

### ISSUE THREAD

**Issue by drmrbrewer** [joelgriffith/browserless#10]
According to [this](https://github.com/joelgriffith/browserless#-docker-quickstart) it is necessary to pass `--shm-size=1gb` to `docker run`.

The problem I have is that I would not be firing browserless up via `docker run` but rather `docker service create`... and it's not possible to pass `--shm-size` as an option to that.  There is a [possible workaround](https://github.com/moby/moby/issues/26714) to pass `--mount` instead, but to cut a long story short... that's not possible for me.

I have encountered this `shm` issue before, when deploying headless chrome to docker in a different way, and for that I am passing the option `--disable-dev-shm-usage` to `puppeteer.launch()`... based on [this advice](https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md#tips).  

These two different options (i.e. `--shm-size=1gb` passed to `docker run` and `--disable-dev-shm-usage` passed to `puppeteer.launch()`) seem to be addressing the same problem, so...

Is it possible to pass a custom option (and in particular, `--disable-dev-shm-usage`) to `puppeteer.launch()` in browserless?

I think, if that were possible, it would solve my problem!

Would it anyway be better to have browserless pass `--disable-dev-shm-usage` to `puppeteer.launch()` *by default*... since there is then no longer any need to advise users to pass `--shm-size=1gb` to `docker run`?  Just a simple `docker run -p 3000:3000 browserless/chrome`.

But that, as well as the ability to pass other custom options, would be nice.

**EDIT** OK now that I look at the browserless launch code, I see that you *do* already pass `disable-dev-shm-usage` to `puppeteer.launch()`... so I suppose that the above question then becomes... is it actually still necessary to pass `--shm-size=1gb` to `docker run` if you're also passing `disable-dev-shm-usage` to `puppeteer.launch()`... aren't they there for the same reason?

**Comment by joelgriffith** [comment]
Great point. To be honest I haven’t tested whether or not the `—disable-dev-shm` flag actually works or not.

You can try expirementing with flags if you’d like (there’s docs on that here: https://docs.browserless.io/docs/chrome.html#other-parameters). Other than that I’ll try and investigate whether or not this does indeed solve the shm issue, and if so update docs accordingly.

**Comment by drmrbrewer** [comment]
Actually, [the link](https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md#tips) I included in the original post seems to make it pretty clear.  It explains the problem that `/dev/shm` is too small in a Docker container, and suggests the solution as being to do `docker run --shm-size=1gb` to increase the size of `/dev/shm`.  This is probably what you based [your instruction](https://github.com/joelgriffith/browserless#-docker-quickstart) on.

But then it goes on to say:

> Since Chrome 65, this is no longer necessary. Instead, launch the browser with the --disable-dev-shm-usage flag

... giving the example:

    const browser = await puppeteer.launch({
      args: ['--disable-dev-shm-usage']
    });

And you're also passing that flag.  So it seems to be the case that, from Chrome 65 onwards, you don't need both... just the flag passed to `puppeteer.launch()`.  If you pass both, you increase the size of `dev/shm` and then render that step pointless by disabling `dev/shm` completely.

However, although these two flags seem to solve the same problem, they apparently do so in different ways.  One is to increase the size of `/dev/shm' while the other is to disable it completely and use `/tmp` instead.  I guess that there may still be a benefit of keeping `/dev/shm' (but making it bigger) *rather than* disabling `/dev/shm' ... i.e. one or the other but not both.

I don't know enough about `/dev/shm' usage to understand which is better in what circumstance.  All I do know is that passing `--disable-dev-shm-usage` to `puppeteer.launch()` works for me (without the `docker run` flag... because I don't do `docker run`).

**Comment by drmrbrewer** [comment]
After some further playing, I'm pretty sure now that these two flags are mutually exclusive... i.e. if you use the `--shm-size=1gb` flag then you don't need the `--disable-dev-shm-usage` flag (because `/dev/shm' is large enough to cope) and if you use the `--disable-dev-shm-usage` then you don't need the `--shm-size=1gb` flag (because you've disabled `/dev/shm' in favour of `/tmp` so there is no point in increasing the size of `/dev/shm').

**Comment by 1600** [comment]
use either of those flags is ineffective in my case.
