### ISSUE TITLE
Karma config using the Docker image

### ISSUE THREAD

**Issue by Megagyger** [joelgriffith/browserless#105]
Id like to use the browserless docker image along with puppeteer to run a suite of karma tests.
I seem to have problems integrating puppeteer to use this docker image instead of the chromium binary.

**What I had working:**
I have puppeeter installed WITH the chromium Download and I am able to execute the tests against this

**What I am trying to do:**
I want to execute the tests against the browserless instead of puppeteers Chromium
So I have a rhel server with browserless image running.
I want to get Karma/puppeteer to use this as chrome when running the suite of tests

**What is happening:**
I installed the puppeteer dependency without the Chromium Download as per documentation
Run the image in a container using the default parameters as per the documentation.
But it looks like puppeteer is still trying to use the chromium that it installs during default install
You can tell this from the output

`
i02 01 2019 11:15:43.738:INFO [karma-server]: Karma v3.1.3 server started at http://0.0.0.0:9877/
02 01 2019 11:15:43.739:INFO [launcher]: Launching browsers ChromeHeadless with concurrency unlimited              14% building modules 38/38 modules 0 active02 01 2019 11:15:43.757:INFO [launcher]: Starting browser ChromeHeadless
02 01 2019 11:15:43.758:DEBUG [temp-dir]: Creating temp dir at /tmp/karma-45225170
02 01 2019 11:15:43.759:DEBUG [launcher]: /software/applications/rjs3-service-admin-ui/node_modules/puppeteer/.local-chromium/linux-609904/chrome-linux/chrome --user-data-dir=/tmp/karma-45225170 --no-default-browser-check --no-first-run --disable-default-apps --disable-popup-blocking --disable-translate --disable-background-timer-throttling --disable-renderer-backgrounding --disable-device-discovery-notifications http://localhost:9877/?id=45225170 --headless --disable-gpu --remote-debugging-port=9222   
`

My question/issue is how do I get/tell Karma to go to browserless docker image?
For example for e2e tests you can just change the url - there are many examples online.
But specifying the chrome to use by puppeteer in a Karma config, I cannot find or se any documentation on the puppeteer repos or here on browserless.

Below is my karma config file, Id imagine I have to do something with the executable path:

`
process.env.CHROME_BIN = require('puppeteer').executablePath();
`
`
    browsers: ['ChromeHeadlessNoSandbox'],
    customLaunchers: {
      ChromeHeadlessNoSandbox: {
        base: 'ChromeHeadless',
        flags: ['--no-sandbox']
      }},
    singleRun: true});}; `

**Comment by Megagyger** [comment]
Id like to use the browserless docker image along with puppeteer to run a suite of karma tests.
I seem to have problems integrating puppeteer to use this docker image instead of the chromium binary.

What I had working:
I have puppeeter installed WITH the chromium Download and I am able to execute the tests against this

What I am trying to do:
I want to execute the tests against the browserless instead of puppeteers Chromium
So I have a rhel server with browserless image running.
I want to get Karma/puppeteer to use this as chrome when running the suite of tests

What is happening:
I installed the puppeteer dependency without the Chromium Download as per documentation
Run the image in a container using the default parameters as per the documentation.
But it looks like puppeteer is still trying to use the chromium that it i meant to install.
You can tell this from the output

`
i02 01 2019 11:15:43.738:INFO [karma-server]: Karma v3.1.3 server started at http://0.0.0.0:9877/
02 01 2019 11:15:43.739:INFO [launcher]: Launching browsers ChromeHeadless with concurrency unlimited              14% building modules 38/38 modules 0 active02 01 2019 11:15:43.757:INFO [launcher]: Starting browser ChromeHeadless
02 01 2019 11:15:43.758:DEBUG [temp-dir]: Creating temp dir at /tmp/karma-45225170
02 01 2019 11:15:43.759:DEBUG [launcher]: /software/applications/rjs3-service-admin-ui/node_modules/puppeteer/.local-chromium/linux-609904/chrome-linux/chrome --user-data-dir=/tmp/karma-45225170 --no-default-browser-check --no-first-run --disable-default-apps --disable-popup-blocking --disable-translate --disable-background-timer-throttling --disable-renderer-backgrounding --disable-device-discovery-notifications http://localhost:9877/?id=45225170 --headless --disable-gpu --remote-debugging-port=9222   
`

My question/issue is how do I get/tell Karma to go to browserless docker image?

Below is my karma config file

`
 process.env.CHROME_BIN = require('puppeteer').executablePath();

module.exports = function (config) {
  config.set({
    basePath: '',
    frameworks: ['jasmine', '@angular-devkit/build-angular'],
    plugins: [
      require('karma-jasmine'),
      require('karma-chrome-launcher'),
      require('karma-jasmine-html-reporter'),
      require('karma-coverage-istanbul-reporter'),
      require('@angular-devkit/build-angular/plugins/karma')
    ],
    client:{
      clearContext: false // leave Jasmine Spec Runner output visible in browser
    },
    coverageIstanbulReporter: {
      dir: require('path').join(__dirname, 'coverage'), reports: [ 'html', 'lcovonly' ],
      fixWebpackSourcePaths: true,
      reporters : ['coverage'],
      preprocessors : {'src/app/*.ts' : 'coverage'}
    },
    angularCli: {
      environment: 'dev'
    },
    reporters: ['progress', 'kjhtml'],
    port: 9876,
    colors: true,
    logLevel: config.LOG_INFO,
    autoWatch: false,
    browsers: ['ChromeHeadlessNoSandbox'],
    customLaunchers: {
      ChromeHeadlessNoSandbox: {
        base: 'ChromeHeadless',
        flags: ['--no-sandbox']
      }
    },
    singleRun: true
  });
};
`

**Comment by joelgriffith** [comment]
Sorry for my delay @Megagyger! Judging by the docs that I've read there isn't direct support for puppeteer yet, however they do support Webdriver (which we offer as a feature). There's a plugin for doing so here: https://github.com/karma-runner/karma-webdriver-launcher. Your `karma.conf.js`, depending on where you launch browserless, would look something like:

```js
module.exports = function(karma) {
  // Change the base URL here, but keep the `/webdriver` which is where browserless listens for requests
  var webdriverConfig = 'http://localhost:3000/webdriver'

  // Rest of your config ...
};
```

I'd be interested in hearing how it works for you as I haven't attempted this myself. Please feel free to report back!

**Comment by Megagyger** [comment]
@joelgriffith In my case I never got to fully see if this worked with your image.
After spending a day at it, I decided to switch tactics and thus opted for the selenium/standalone-chrome image and with that I could use the selenium launcher plugin.

Also, I had a firewall issue, so I cannot say if all those attempts I had with your image would actually have worked or not (with the script launcher/webdriver), maybe they would have.

**Comment by joelgriffith** [comment]
No worries, apologies that it took so long. I'll give this a spin sometime soon and see if we can't figure it out. I'll close this for now then!
