### ISSUE TITLE
HTTP/1.1 400 The module 'lighthouse' is not whitelisted in VM.

### ISSUE THREAD

**Issue by pos1tron** [joelgriffith/browserless#107]
I'm running the browserless docker container in a kubernetes cluster.

When I POST to the `/stats` endpoint, I get the following error:

>HTTP/1.1 400 The module 'lighthouse' is not whitelisted in VM.

**Comment by joelgriffith** [comment]
Yeah, this is definitely something we could do a better job of. Right now we have pretty tight restrictions on module whitelisted to be “secure by default,” but you can disable that with this flag: https://docs.browserless.io/docs/docker.html#exposing-external-modules-to-function

**Comment by pos1tron** [comment]
Thanks! I was able to add `-e "FUNCTION_EXTERNALS=[\"lighthouse\"]" -e "FUNCTION_BUILT_INS=[\"url\"]"`, and now it's working.

**Comment by lonkle** [comment]
I'm having this same issue (`The module 'puppeteer-extra' is not whitelisted in VM`) except the only difference is I'm using an ENV variable from within the `Dockerfile` itself:

`ENV FUNCTION_EXTERNALS [ "puppeteer-extra"]`

**If** I don't add that line to the` DOCKERFILE` then Browserless sends back a `puppeteer_extra is not defined` error so the ENV variable does work. But why allow it but not whitelist it at the same time? I'm

**Comment by lonkle** [comment]
I tried hardcoding `puppeteer-extra` in config.ts which almost worked but now I get the error: `Module 'puppeteer-extra' is not allowed to be required. The path is outside the border!` I'm getting closer. 😅

**Comment by lonkle** [comment]
Yup, that was definitely the wrong way to go. So, I need to require it and whitelist it. Browserless is supposed to do both with that variable but `VM` is still blocking it for some reason.
