### ISSUE TITLE
user-data-dir

### ISSUE THREAD

**Issue by drmrbrewer** [joelgriffith/browserless#11]
In order to get caching of [service workers](https://developers.google.com/web/fundamentals/primers/service-workers/) working in browserless (and puppeteer generally) I find that it's necessary to set a `userDataDir` via the `--user-data-dir` passed to `puppeteer.launch()`.  This may be necessary to get plain http caching working too... not sure.

You can see (for service worker caching) this via the following... when the flag is passed via the `ws`, the browser is able to cache the content in the service worker, and subsequently (after the content has been cached) you'll see "retrieved from service worker cache".  Without the flag, you just get "retrieved from network" no matter how many times you request the content.

    (async () => {
      const browser = await puppeteer.connect({
        browserWSEndpoint: 'ws://browserless.mydomain.com:3000?--user-data-dir=/tmp'
      });
      const page = await browser.newPage();
      const url = 'https://cloud3squared.com/files/sw-stackoverflow-demo/index.html';
      await page.goto(url, { waitUntil: 'networkidle0' });
      await page.screenshot({ path: './temp.png' });
      browser.close();
    })();

This is fine when only one browser has been instantiated by browserless under the hood.  The problem comes when multiple browsers are all passed the same `--user-data-dir` and are all trying to access and write to the same storage area.

At least, I'm seeing a few issues when using browserless which I *think* result from this.  It's partly educated guesswork at this stage.

I wonder if it's necessary to be able to somehow use a different `--user-data-dir` for each different browser that is instantiated, so that there is no conflict?  

Or maybe it's possible to use `/dev/shm` (if it's big enough and [hasn't been disabled](https://github.com/joelgriffith/browserless/issues/10#issuecomment-370391046)) for `--user-data-dir` (I think that `/dev/shm` is "supposed" to be shared between different processes) ... I haven't yet tried that ... mainly because I can't since browserless disables `/dev/shm` by default.

P.S. the page rendered by browserless when "fetched from network" in the above example seems to be missing (unable to render) [this character](http://www.codetable.net/hex/2718)... the "tick" is rendered fine (for "fetched from service worker cache")

**Comment by joelgriffith** [comment]
@drmrbrewer I'd be curious to see if `/dev/shm` fixes this issue (and if so we should probably _not_ disable it and instead use the `--dev-shm-size`). I understand that this somewhat overlaps with https://github.com/joelgriffith/browserless/issues/10 if that's the case.

Feel free to make a branch and remove that `--dev-shm-size` to see if that fixes the caching issue. Otherwise there's likely another flag someplace that's overriding the service worker behavior.

**Comment by drmrbrewer** [comment]
OK after some further playing I'm pretty sure that supplying `userDataDir` to `browser.launch()` is not necessary to get service worker caching working... if you don't supply on then puppeteer will create a `userDataDir` for you, and delete it on `browser.close()`.  Furthermore, a separate `userDataDir` is created for each `browser` so there is no conflict.  Therefore there is little point in passing `userDataDir` IMHO, and therefore no need to ensure that a different `userDataDir` is used per browser (because puppeteer does this for you).  Maybe it would be a bit faster on a `tmpfs` mount like `/dev/shm` but I can't imagine the difference would be significant enough to worth worrying about.
