### ISSUE TITLE
Latest release breaks html screenshots

### ISSUE THREAD

**Issue by mattwoods11** [joelgriffith/browserless#112]
A change was introduced in #106 to support new functionality/fixes in the latest version of Puppeteer. I've tested both the latest version release-puppeteer-1.11.0 and release-puppeteer-1.9.0(the version I'm currently still using). In both instances the screenshot is no longer captured when giving the screenshot endpoint HTML instead of a URL. 

```{
  "html": "<html>HTML Content</html>",
  "options": {
    "fullPage": true,
    "type": "png"
  },
	"gotoOptions": {
    	"waitUntil": "networkidle2"
    }
}
```

![release-puppeteer-1 9 0-srn](https://user-images.githubusercontent.com/6618417/51248848-68105880-195f-11e9-87e9-ef50cd81aab6.png)

Additionally, this change was only meant for the newer versions of Puppeteer but it looks like it was built against the older releases as well. I would assume #86 will fix this in the future.

**Comment by joelgriffith** [comment]
Sorry for the regression. Should be good to go now
