### ISSUE TITLE
Caching performance

### ISSUE THREAD

**Issue by drmrbrewer** [joelgriffith/browserless#12]
As a consequence of the fact that each `browser` keeps its own separate `userDataDir` by default, and since browserless maintains a pool of browsers to serve incoming requests, it seems to me that caching will be somewhat sub-optimal... for N browsers there are N caches to fill, more cache misses, and more cached data.

Is there any way to ensure that the same `browser` (and associated cache) is used for the same source, so that a consistent cache is used for a particular user?  Perhaps based on some ID or key, or even IP address?

Ideally a common cache area would be used for all browsers, but I'm not sure this is possible without horrible conflicts.  I did try passing the same `userDataDir` to all browsers and indeed it didn't work out well.  Perhaps using a shared memory mount (`/dev/shm`) would work better since that is "supposed" to be shared between processes?

**Comment by joelgriffith** [comment]
Let's take this up on the Slack channel, but going to close this for now since it's not _really_ a bug but a perf improvement.
