### ISSUE TITLE
Example with RSpec & Capybara + Docker?

### ISSUE THREAD

**Issue by tibbon** [joelgriffith/browserless#121]
I've been having some problems getting Rspec & Capybara to play well with Docker. 

```
Capybara.register_driver :chrome do |app|
  chrome_options = Selenium::WebDriver::Remote::Capabilities.chrome(
    chromeOptions: { args: %w(headless disable-gpu --no-sandbox --disable-dev-shm-usage) }
  )
  Capybara::Selenium::Driver.new(app,
    browser: :remote,
    desired_capabilities: chrome_options,
    url: 'http://localhost:3000/webdriver'
  )
 end

  Capybara.javascript_driver = :chrome
  Capybara.server = :webrick
```

Yet, all my pages come back blank it seems.  Ideas?

**Comment by joelgriffith** [comment]
We generally see blank pages when the site itself is blocking automated access (by some means).

Have tried seeing if there’s anything peculiar about the logs: https://docs.browserless.io/docs/docker.html#logging?

**Comment by tibbon** [comment]
I think I may have realized one of my problems; I'm running RSpec on my local machine and attempting to use Docker + Browserless in a VM, which perhaps doesn't have access to the localhost? I'll dig through the logs more tomorrow and see what I can pull over to share. Thanks!

**Comment by joelgriffith** [comment]
If you give it a port mapping it should be addressable from localhost: `docker run -p 3000:3000 -e "DEBUG=browserless*" browserless/chrome:latest`. You can do a quick sanity check by hitting the debugger from your webrowser: http://localhost:3000/

**Comment by joelgriffith** [comment]
@tibbon did you get to the bottom of this?
