### ISSUE TITLE
License

### ISSUE THREAD

**Issue by seeekr** [joelgriffith/browserless#122]
Hi,

I was wondering about the license that applies to this repository. Could you please clarify that?

There is no LICENSE file, and the README speaks about hosted options and a commercial license, for which it is unclear to me about who needs to buy that and who doesn't. I would have to guess that open source projects are supposed to be able to use the code without a commercial license (and assume GLPv3 to apply), and any other project which is not using the hosted version, should buy a commercial license?

Thanks!

**Comment by joelgriffith** [comment]
Great point, we'll get a LICENSE.txt file shortly. You're correct in your guess though, we'll be using a GLPv3 license, so OS projects are free to use it. Paid/commercial projects should seek a commercial license as this allows them to keep their software proprietary.

**Comment by joelgriffith** [comment]
License is now added to the repo, apologies for any confusion or issues! Thanks for your patience
