### ISSUE TITLE
versioned dockerhub release with the latest updates

### ISSUE THREAD

**Issue by pos1tron** [joelgriffith/browserless#123]
Hey there friend. I see that latest has been updated in Dockerhub, but not seeing a versioned release. Could we get a versioned dockerhub release with the latest updates?

**Comment by joelgriffith** [comment]
Yes -- I have a few other updates in the debugger I'll get in tonight (I'm on PST) and do a release

**Comment by joelgriffith** [comment]
PR is merged, going to update changelog and deploy
