### ISSUE TITLE
Dockerhub tag for build with puppeteer-1.1.1

### ISSUE THREAD

**Issue by AndyMathys** [joelgriffith/browserless#13]
Hello,

I was wondering if it would be possible to create a tag on Docker Hub for the build with puppeteer-1.1.1
I'd prefer to use this over latest to prevent potentially breaking changes being pulled when I'm rebuilding my service.

Thanks a lot,
Andy

**Comment by joelgriffith** [comment]
https://hub.docker.com/r/browserless/chrome/builds/b27bdpx7xh9gzqfdchxbdwg/

**Comment by AndyMathys** [comment]
Thanks!
