### ISSUE TITLE
/screencast duration is not precise

### ISSUE THREAD

**Issue by html5maker** [joelgriffith/browserless#132]
Hi,
There are a few issues with the screencast api because it doesn't allow to invoke start recording and stop recording manually.

Start recording - when page has some async scripts - I want to listen for some event and start recording only after this event (not on **window.onload**).
Stop recording - current implementation with **await page.waitFor(3000);** is not precise (it doesn't stop recording immediately) and it records about 100ms more than expected. It would be nice to call stop recording manually after **page.waitFor**:

`await page.goto('index.html');

    await page.waitFor(function () {
        return window.my_async_scripts_loaded;
    });

    await page.evaluate(function () {
        window.postMessage({type: 'REC_START'});
    });

    await page.waitFor(3000);

    await page.evaluate(function () {
        window.postMessage({type: 'REC_STOP'});
    });`

**Comment by joelgriffith** [comment]
I think we can inject start/stop functions for better control:

```
module.exports = async ({ page, startRecording, stopRecording }) => ...
```

What do you think @html5maker?

**Comment by html5maker** [comment]
Sounds good! 👍

**Comment by joelgriffith** [comment]
Haven’t forgotten about this. Tricky to make it backwards compatible so it’s taking some time.

**Comment by joelgriffith** [comment]
This is now on master (and latest in docker). Your functions can now programatically start and stop (only once) the recording:

```
module.exports = async({ page, startScreencast, stopScreencast }) => {
	await page.goto('https://codepen.io/simurai/pen/crieh');
	startScreencast();
	await page.waitFor(10000);
	stopScreencast();
};
```

**Comment by vbarbarosh** [comment]
Although your code works, the following doesn't:
```
async function main({page, startScreencast, stopScreencast})
{
    await page.goto('https://vclock.com/stopwatch');
    await page.click('#btn-resume');
    startScreencast();
    await page.waitFor(5000);
    stopScreencast();
}
module.exports = main;
```
It works if I remove `startScreencast` and `stopScreencast`:
```
async function main({page})
{
    await page.goto('https://vclock.com/stopwatch');
    await page.click('#btn-resume');
    await page.waitFor(5000);
}
module.exports = main;
```
Is it intentional?

**Comment by joelgriffith** [comment]
@vbarbarosh yeah this does look like a bug, your code should work that way. I'll take a look here soon

**Comment by html5maker** [comment]
@joelgriffith any updates on this?

**Comment by joelgriffith** [comment]
Yup -- I'll be addressing this later today

**Comment by joelgriffith** [comment]
Fixed in https://github.com/joelgriffith/browserless/pull/182
