### ISSUE TITLE
Date format

### ISSUE THREAD

**Issue by felipemsantana** [joelgriffith/browserless#134]
Is there a way to change the date format of the browser? I need for the date in the PDF header.
I think it's possible in puppeteer by setting the `--lang` argument.

https://stackoverflow.com/a/47292022

But I couldn't find a way to pass args to Chrome. Am I missing something?

**Comment by joelgriffith** [comment]
Yup, we support setting custom launch flags via querystring parameters. There’s a call out at the bottom of this page: https://docs.browserless.io/docs/chrome-flags.html#docsNav

Let me know if that doesn’t work for you, or if something else is wrong!

**Comment by felipemsantana** [comment]
This does not work for prebooted Chrome
https://github.com/joelgriffith/browserless/blob/56dc37da74021391deaf3dfd2f594b935a3003bc/src/puppeteer-provider.ts#L80

**Comment by felipemsantana** [comment]
After setting values for `LANG` and `LANGUAGE` env vars to change Ubuntu's language it worked.
