### ISSUE TITLE
Download is not saved if initiated in new tab.

### ISSUE THREAD

**Issue by shaminmv** [joelgriffith/browserless#140]
After trying a lot with puppeteer to download a file that opens in a new tab I switched to browserless because chromium crashes when download starts on new tab.

But I still I am unable to download the file. Here is the dumpio i get on puppeteer. 
`[0227/222012.378:ERROR:process_memory_win.cc(73)] ReadMemory at 0x268de00025c of 512 bytes failed: Only part of a ReadProcessMemory or WriteProcessMemory request was completed. (0x12B)`

Are there any settings I need to follow to download the file? I have used the setDownloadBehavior

**Comment by joelgriffith** [comment]
You'll likely need to alter the download behavior of the new tab as it'll likely default to the original download directory:

```js
// Inject download behavior on new targets
browser.on('targetcreated', async (target) => {
  const page = await target.page();
  await page._client.send('Page.setDownloadBehavior', {
    behavior: 'allow',

    downloadPath: '/some/download/path',
  });
});
```

However, your message looks like it's trying to (maybe) write someplace that it can't?

**Comment by joelgriffith** [comment]
Going to close this since it's not apparent to me that it's a bug in browserless, but happy to continue chatting.
