### ISSUE TITLE
Browserless docker: connect ECONNREFUSED 127.0.0.1:<port>

### ISSUE THREAD

**Issue by TAnas0** [joelgriffith/browserless#144]
Hello @joelgriffith ,

First off thanks for Browserless, solid work.

Basically, I am running Browserless in docker behind a web server, also dockerized, which is [Caddy](https://github.com/abiosoft/caddy-docker).

Browserless works fine when accessed directly, from the browser or its endpoints.
But trying to access it through Caddy **sometimes** fails and responds with a `502 Bad Gateway error`, which when tracked in the logs of Browserless, leads us to an error message of the following format, where `<port>` kind of random and is higher than 30000:

```bash
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED 127.0.0.1:<port>
```
My belief is that the port in question is the one talked about in this [comment](https://github.com/GoogleChrome/puppeteer/issues/330#issuecomment-323068332). Am I right?

I am sure that this has to do with the networking setup of Caddy and between the docker images.

I have two questions:
- Would a Docker Compose solve the problem?
- If yes, then is there an alternative way to pass the parameters in this [comment](https://github.com/joelgriffith/browserless/issues/107#issuecomment-453255496)? Since it seems that I cannot specify them in YAML syntax in the `docker-compose.yaml`

Also, the scenario in which this behavior happens, is when I make several (5) parallel asynchronous request to the same endpoint, where one gets processed perfectly fine, and then next (which when, i guess, a new port allocation happens) fails, and leads to all 5 requests to fail too (just as coded).

I know my situation and setup is too special and that the problem and solution both lie outside of Browserless, but I would really appreciate if anybody can shed some light into the situation.

Cheers

**Comment by joelgriffith** [comment]
Hey there! Sorry to hear you’re having issues. There’s always _one_ exposed external port (generally `3000`), and potentially many ports opened by Chrome when it starts. My suspicion is that something is failing when Chrome tries to open its port, and the web server tries proxy the external port to chromes.

Docker composer should easily accept environment variable args, and I can share mine for our demo box. It’d be good to hear from you what API you’re trying to use and what configuration you’re trying to use?

**Comment by TAnas0** [comment]
Hey,

Agree, I am fairly certain that this is the point of failure:
> web server tries proxy the external port to chromes

The endpoint that I am trying to use is the `/stats` endpoint where the Lighthouse reports are ran.
I am also experimenting with the [`MAX_CONCURRENT_SESSIONS`](https://docs.browserless.io/docs/docker.html#max-concurrent-sessions) parameter, which thanks to, *correct me if I am wrong*, I can run multiple Lighthouse audits in *parallel*.

I am sending the 5 POST request to the endpoint at the same time, all fail but one (the first to arrive, I guess).

To not get too deep into the specifics of my situation, I suppose that a working example of Browserless launched through Docker Compose, with the endpoint `/stats` exposed would solve my issue.

Let me know if you need anything

**Comment by joelgriffith** [comment]
Yes, that's correct, you should be able to run these in parallel. I've noticed that they're quite taxing to run resource-wise.

I'll take a look and see if I can't find the issue.

**Comment by TAnas0** [comment]
Hey,
I just pinpointed even further the source of the problem. It is related to Lighthouse as an NPM module: https://github.com/GoogleChrome/lighthouse/issues/7187

The issue is definetely not related my Caddy web server. Found out by running Browserless with this `docker-compose.yaml`:

```
version: '3'
services:
  browserless:
    image: browserless/chrome:latest
    container_name: "browserless"
    environment:
      - DEBUG=browserless/chrome
      - MAX_CONCURRENT_SESSIONS=10
      - FUNCTION_EXTERNALS=["lighthouse"]
      - FUNCTION_BUILT_INS=["url"]
    ports:
      - 3000:3000
```

Then simply request several Lighthouse audits from the endpoint `/stats` and you will notice the weird behavior I talked about earlier: first audit succeeds, all else fails at the same time, with the error message: `no known mark: lh:gather:afterPass:Accessibility`, which led me to the above linked issue.

I'll check the issue further and get back to you.

If there is room for improvement concerning the Lighthouse module, I think it might be a good opportunity to contribute.
Do you have any plans/todos for Lighthouse on the radar?

**Comment by joelgriffith** [comment]
Yeah, the issues is definitely in LH: https://github.com/GoogleChrome/lighthouse/issues/7187. Browserless doesn't run LH, or any functions, in a child process _yet_. Currently they're ran inside VM2, but can be migrated over to using child processes. Unfortunately this is a pretty large task to handle, so I'll work towards implementing it this weekend if it's possible

**Comment by TAnas0** [comment]
https://github.com/GoogleChrome/lighthouse/issues/7104 is about the error as well.

If Lighthouse can be run in parallel with Browserless, then this would be a neat feature.

I am by no means an advanced developer and not yet familiar with Browserless internals, but let me know if I can help

**Comment by Songkeys** [comment]
@TAnas0 

Hi, sorry about asking in this closed issue. I'm also using Caddy to serve. But I can't get it running on https and wss. The plain IP address can however. My Caddyfile is:
```
domain {
  tls [my email]
  reverse_proxy /* http://127.0.0.1:3000
}
```

Any further configurations should I add? Thank you so much if you could help me.
