### ISSUE TITLE
PayloadTooLargeError: request entity too large

### ISSUE THREAD

**Issue by tjipz8** [joelgriffith/browserless#150]
I'm trying to generate large pdf by sending huge html string and encounter this error.

Is this because it hard coded here ?https://github.com/joelgriffith/browserless/blob/31f6f5dc34e20afb96528d1ecffe6ef489a38e2d/src/routes.ts#L48

**Comment by joelgriffith** [comment]
Yup, that’s exactly it! I’m in the process of reworking the config utility and will add this as an option

**Comment by tjipz8** [comment]
thanks

**Comment by joelgriffith** [comment]
https://github.com/joelgriffith/browserless/pull/151 will address this!
