### ISSUE TITLE
Session closed. Most likely the page has been closed

### ISSUE THREAD

**Issue by jamiel-sharief** [joelgriffith/browserless#152]
I have a long script which works fine when using `puppeteer.launch`, but the moment i connect to the browserless docker image with `puppeteer.connect`, I get strange errors. 

I think the connection is timing out, due to time on the page, however i cant see how to change that and it is only happening with browserless.  Is there a way to configure this?
[Possible Related](https://github.com/miyakogi/pyppeteer/issues/175)

```
Error: Protocol error (Target.activateTarget): Session closed. Most likely the page has been closed.
    at CDPSession.send (/var/www/nodejs/node_modules/puppeteer/lib/Connection.js:180:29)
    at Page._screenshotTask (/var/www/nodejs/node_modules/puppeteer/lib/Page.js:875:24)
    at <anonymous>
  -- ASYNC --
    at Page.<anonymous> (/var/www/nodejs/node_modules/puppeteer/lib/helper.js:110:27)
    at processPage (/var/www/nodejs/puppeteer-demo.js:195:14)
    at <anonymous>
```

**Comment by joelgriffith** [comment]
Do you have a connection timeout set? How large is the page and what kind of machine is running the image?

Generally this happens when the page is closed via the timer in Browserless. However it’s default set to around 5 minutes.

**Comment by jamiel-sharief** [comment]
The web page is processing is 400kb with about 100 elements on it that being read. The process only takes about a 1-1.5 minutes mainly because delays which are put through to ensure it doesnt go through too quicky which then can cause other issues.

This is the code I use to connect, so i am not setting any timeout.
```
async function getBrowser(){
    if(config.browserless === false){
      return await puppeteer.launch({headless: false});
    }
    return await puppeteer.connect({
        browserWSEndpoint: config.browserless
    });
}
const browser = await getBrowser()
```

The socket is closed during this
```
await page.waitFor(10000)
```
The machine is MacBook air, 8GB  I7.

**Comment by jamiel-sharief** [comment]
I have digged into this, and browserless is closing the connection after 1 minute of execution. How can i change this?

**Comment by joelgriffith** [comment]
Have you tried setting a connection timeout? Docs for that are here: https://docs.browserless.io/docs/docker.html#connection-timeout. Setting it to -1 will disable the timeout, which would be good to try for an initial test

**Comment by jamiel-sharief** [comment]
Awesome, this worked. Sorry not sure I missed this. I am setting to 5 minutes to ensure that I can benefit from closing zombie sessions. Note. It times out after a minute and not 30 seconds as the manual says. Is this because the 30 seconds occur whilst it is doing vs the time executing the script?

**Comment by joelgriffith** [comment]
Yeah, there's two timers at play here: one is the "global" session debugger that puppeteer uses. The second is puppeteer's per-method timeout (set to 30 seconds by default). You can configure both, and I'd recommend setting the browserless timeout to something higher like 5 minutes.

What manual are you referring to (or the page)?

**Comment by jamiel-sharief** [comment]
[The value of which can be set in milliseconds, and defaults to 30000, or 30 seconds](https://docs.browserless.io/docs/docker.html#connection-timeout)

**Comment by joelgriffith** [comment]
Awesome. I'll update those docs in a bit and close this out for now. Appreciate the link!
