### ISSUE TITLE
Proxy per page?

### ISSUE THREAD

**Issue by Raidus** [joelgriffith/browserless#16]
Hey!

One can set a proxy like:

```javascript
  const browser = await puppeteer.launch({
    headless: false,
    args: [
      '--proxy-server=PROXY_URI'
    ],
  });
```

Is there a possibility to set different proxies for different pages in the same browser instance?
Like:
```
browser1, page1 => proxy1
browser1, page2 => proxy2
```

Cheers

**Comment by joelgriffith** [comment]
Can't do it on a per-page level, but you _can_ do it at the `puppeteer.connect` level: https://docs.browserless.io/docs/chrome.html#launching-with-a-proxy (note that you'd replace the `wss://chrome.browserless.io/` with wherever the host is running.

**Comment by joelgriffith** [comment]
I'm going to close this since the feature-set is there, however it's not exposed on a per-page level (feel free to continue discussing)
