### ISSUE TITLE
Chrome preboots always with defaults args and actually never gets used

### ISSUE THREAD

**Issue by Alex0007** [joelgriffith/browserless#166]
Environment variables
```
    - DEBUG=browserless*
    - EXIT_ON_HEALTH_FAILURE=true
    - PREBOOT_CHROME=true
    - KEEP_ALIVE=true
    - CONNECTION_TIMEOUT=60000
    - MAX_QUEUE_LENGTH=0
    - MAX_CONCURRENT_SESSIONS=5
    - ENABLE_DEBUGGER=false
```

Logs 
```
browserless:job VxJmtoi_d: Adding new job to queue.        
browserless:job VxJmtoi_d: Getting browser.
browserless:system Using pre-booted chrome: false
browserless:chrome-helper Launching Chrome with args: {
 "args": [
 "--user-data-dir=/tmp/session-123",
 "--no-sandbox=true",
 "--disable-setuid-sandbox=true",
```

After retrying same request i see same output. 

So it seems that browserless do not aggregate previous calls and always pre-boots browsers with default settings (and these instances are not used)

<hr>

```
browserless:job VxJmtoi_d: Cleaning up job
browserless:job VxJmtoi_d: Browser not needed, closing
browserless:job VxJmtoi_d: Browser cleanup complete, checking swarm.
```

At the end of request i see that browser "is not needed". Why? `KEEP_ALIVE=true`
(in my code i'm using `browser.disconnect()` not `browser.close()`)

**Comment by joelgriffith** [comment]
Hey @Alex0007, are you specifying flags when connecting? Anytime you specify custom arguments or other options then it's impossible for browserless to use a pre-booted Chrome (since there's a discrepancy in the launch args).

If that's not the case then I think this is a legit bug. Would you mind sharing details of how you're connecting?

**Comment by Alex0007** [comment]
@joelgriffith 
Yes, i'm specifying same `--proxy-server` flag (in 99% of calls). I guess, some configuration can be exposed to be able to specify pre-boot arguments. Or browserless can create chrome instances with arguments used last time

But [defaultLaunchArgs](https://github.com/joelgriffith/browserless/blob/master/src/chrome-helper.ts#L61) is used everytime to pre-boot and this is not configurable

**Comment by joelgriffith** [comment]
I believe all the `launchArgs` are stringify-able so we can probably include an environment variable that's some JSON for it?

**Comment by yifeikong** [comment]
@joelgriffith that would be great, also enables us to use a persistent userDataDir across docker container reboots.

**Comment by yifeikong** [comment]
> Anytime you specify custom arguments or other options then it's impossible for browserless to use a pre-booted Chrome (since there's a discrepancy in the launch args).
Could we reuse old instance with the same arguments?

**Comment by yifeikong** [comment]
I have open a PR for setting launch args for preboot instances. I could set data-dir for instance like this docker-compose file:

```
version: '3'

services:
  browserless:
    image: chrome
    network_mode: host
    # ports:
    #   - "3000:3000"
    shm_size: 2gb
    environment:
      - CONNECTION_TIMEOUT=60000
      - MAX_CONCURRENT_SESSIONS=4
      - MAX_QUEUE_LENGTH=10
      - PREBOOT_CHROME=true
      - EXIT_ON_HEALTH_FAILURE=true
      - KEEP_ALIVE=true
      - HOST=10.40.10.40
      - LAUNCH_ARGS={"args":["--user-data-dir=/data-dir"]}
      - DEBUG=browserless*
    volumes:
      - "./data-dir:/data-dir"
```

Browserless uses a user called `blessuser` inside docker. When using data-dir outside of docker. *be careful with the permissions of mounted dirs.* I use `chmod -R 777 ./data-dir` to make it work.

**Comment by joelgriffith** [comment]
https://github.com/joelgriffith/browserless/pull/173 should fix this -- and good not on the perms of this. I should note that in docs!

**Comment by joelgriffith** [comment]
@yifeikong fixed in https://github.com/joelgriffith/browserless/pull/173, closing

**Comment by Alex0007** [comment]
@joelgriffith 

I guess here is a logical error. Args can be empty and it's OK
https://github.com/joelgriffith/browserless/blob/fa3f04d32c810999d6a4a36cac6011c6860f8d31/src/chrome-helper.ts#L224

For example, 
DEFAULT_LAUNCH_ARGS=["--proxy-server=http://185.124.86.10:3128"]

I want to make request **without** proxy. So i'm not passing any args. Instead of this, proxy specified above is used
