### ISSUE TITLE
How do I pass launch options to self hosted containers?

### ISSUE THREAD

**Issue by yifeikong** [joelgriffith/browserless#167]
I can see there are options for browserless.io services. https://docs.browserless.io/docs/chrome-flags.html.

Are these options usable in self-hosted containers, even for PREBOOT ones?

**Comment by joelgriffith** [comment]
Going to track this in https://github.com/joelgriffith/browserless/issues/166, closing this since it's somewhat a duplicate. Be sure to track 166!
