### ISSUE TITLE
Browserless usage with Pychrome

### ISSUE THREAD

**Issue by Rhynorater** [joelgriffith/browserless#177]
Hello,

I'm using pyChrome for hooking into Chrome Dev Tools. Does browserless support a way to expose the debug interface commonly located on 9222? Do you just have to let it through docker?

Thanks,
Justin

**Comment by joelgriffith** [comment]
We actually only bind to one port, and let chrome do a random port assignment when starting. You should be able to do the following (I haven't checked this, hypothetically it should just work ™️ ):

```
# Assuming you start the container with -p 3000:3000
browser = pychrome.Browser(url="http://127.0.0.1:3000")
```

**Comment by joelgriffith** [comment]
Going to close this, but feel free to discuss!
