### ISSUE TITLE
DEFAULT_LAUNCH_ARGS is used, when i passing no args in my call

### ISSUE THREAD

**Issue by Alex0007** [joelgriffith/browserless#179]
I'm passing some args to `DEFAULT_LAUNCH_ARGS` env var. But then i want to start chrome without them

My comment in closed issue

https://github.com/joelgriffith/browserless/issues/166#issuecomment-492967355

**Comment by joelgriffith** [comment]
I think, given your comment, the best bet would be to (by default) _not_ launch with a proxy in the `DEFAULT_LAUNCH_ARGS` and then "opt-in" via a request parameters. Otherwise it defeats the purpose of having default launch args.

**Comment by Alex0007** [comment]
Request without proxy is a 1% of all requests. 99% are with proxy

**Comment by joelgriffith** [comment]
Yeah, I can see the frustration here. How about doing the following in your `connect` call: `?--proxy-server`. This appears to work locally even though it's a bit odd.

**Comment by Alex0007** [comment]
@joelgriffith 
Hacky, but working

Can be closed?

**Comment by joelgriffith** [comment]
Yup, I think so, will have to add this to docs since it's an interesting behavior.
