### ISSUE TITLE
Launch browserless with '--disable-web-security', with and without token has different results

### ISSUE THREAD

**Issue by ksyke** [joelgriffith/browserless#180]
Hi there,

Thank you for the hard work. 
Just as the title implies, I'm trying to access a page that renders images on a canvas. 
As I've encountered CORS errors, I tried adding '--disable-web-security' which works great on the demo. But as soon as I've added the token, the CORS problems returns.

Here is my code using token:
`const browser = await puppeteer.connect({`
 ` browserWSEndpoint: 'wss://chrome.browserless.io?token=MY-TOKEN&--disable-web-security'`
`});`

Here is my code without token:
`const browser = await puppeteer.connect({`
 ` browserWSEndpoint: 'wss://chrome.browserless.io?--disable-web-security'`
`});`

Did i do something wrong when adding my token?

**Comment by joelgriffith** [comment]
Nope, we do some mangling with flags for usage-accounts. I'm assuming yours is usage-based? I have a build going now that should address this (just as a heads up)

**Comment by ksyke** [comment]
@joelgriffith Thanks for the fast response and yes i do have a usage-based account. Is there an estimate when the build will be released?

**Comment by joelgriffith** [comment]
Should be a few minutes here, takes about ~10 minutes to build

**Comment by joelgriffith** [comment]
@ksyke should be fixed now, closing!

**Comment by ksyke** [comment]
@joelgriffith Checked again and confirmed, new build fixed it. Thanks!

**Comment by williamoliveira** [comment]
Doesn't seems to be working anymore

**Comment by yarzc0de** [comment]
it's not work anymore
