### ISSUE TITLE
blockAds causes TimeoutError

### ISSUE THREAD

**Issue by Alex0007** [joelgriffith/browserless#183]
While this snippet works, when ads blocking is disabled, it fails when `&blockAds` is used

```ts
import * as puppeteer from "puppeteer";

(async () => {
    const browser = await puppeteer.connect({browserWSEndpoint: 'ws://localhost:3000?&blockAds'})
    const page = await browser.newPage();

    console.log('LOADING');
    await page.goto('https://news.abs-cbn.com/news/05/22/19/former-ombudsman-carpio-morales-on-hong-kong-trip-i-was-detained')
    console.log('LOADED');
})();
```

**Comment by Alex0007** [comment]
Related to latest puppeteer
https://github.com/GoogleChrome/puppeteer/issues/4463

**Comment by joelgriffith** [comment]
Likely due to a network request that’s causing the page to fail. Unfortunately some sites can tell if ads are blocked and fail to load.

**Comment by joelgriffith** [comment]
I can't reliably reproduce this.. the page is rather slow even with blockAds, so that might be something to think about. Also, there is a typo in your connect call, URL should be:

`ws://localhost:3000?blockAds`

**Comment by Alex0007** [comment]
@joelgriffith 

https://mixcloud.com/johndigweed

Here is example of URL that causes timeout when using `blockAds`
(puppeteer `load` event)
(puppeteer `domcontentloaded` works though)
