### ISSUE TITLE
Feature Request: allow option to disable the debugger

### ISSUE THREAD

**Issue by michaelwills** [joelgriffith/browserless#19]
Per our conversation @joelgriffith, I am submitting this request to be able to disable the front-end debugger altogether. Maybe `HEADLESS=true` would just off the web ui?

Thanks much!

**Comment by joelgriffith** [comment]
Would `DISABLE_DEBUGGER` work ok? `HEADLESS` might be an overloaded term considering the image this wraps over :)

**Comment by joelgriffith** [comment]
Just a heads up that this is now implemented [over here](https://github.com/joelgriffith/browserless/blob/master/src/index.ts#L16). Closing!
