### ISSUE TITLE
Possible EventEmitter memory leak

### ISSUE THREAD

**Issue by AlexandreAWE** [joelgriffith/browserless#20]
Hi,

This [page](https://docs.browserless.io/docs/best-practices.html) explain that is a good practice to close browser connection after some processing.

After 10 connections, Browserless container throw this log : 

```(node:26) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 SIGHUP listeners added. Use emitter.setMaxListeners() to increase limit```

Here is an example : 
1. Mount a Browserless container on Docker : 
```docker run -p 3000:3000 browserless/chrome:release-puppeteer-1.3.0```

2. Exec this code example : 
```javascript
const puppeteer = require('puppeteer');

(async function () {

    // Synchronous Loop
    for (let i = 0; i < 20; i++) {
        const browser = await puppeteer.connect({
            browserWSEndpoint: `ws://127.0.0.1:3000`,
        });

        const page = await browser.newPage();

        try {
            await page.goto('https://www.google.com');
            await page.screenshot({
                path: './browserless.png'
            });
            browser.close();

            await new Promise(resolve => setTimeout(resolve, 5000));
            console.log('close: ' + i)
        } catch (error) {
            console.error({
                error
            }, 'Something happened!');
            browser.close();
        }
    }
})();```

After 10 loops, a warning happened on Browserless container terminal.

**Comment by AlexandreAWE** [comment]
Well I have found the problem : 
https://github.com/joelgriffith/browserless/compare/1.3.0...master#diff-fcbd5ffe11ed99a24fd9bdec26ae790fR441

When I roll back to chrome.close(), the warn go away

**Comment by joelgriffith** [comment]
@AlexandreAWE interesting... so doing `chrome.process().kill('SIGKILL');` causes the leak? I can definitely remove that if it's the issue (it was an attempt to ensure that chrome does close as it sometimes sticks around...))

**Comment by joelgriffith** [comment]
@AlexandreAWE this should now be closed in all builds, thanks for filling this!

**Comment by AlexandreAWE** [comment]
@joelgriffith I'm not sure but when using ```chrome.close()``` puppeteer lib remove all events listeners : https://github.com/GoogleChrome/puppeteer/blob/3b03ff65c7b369debfcaa67a8673fba105a2d20d/lib/Launcher.js#L172

When using ```chrome.process().kill('SIGKILL');``` some listeners are not cleaned.
