### ISSUE TITLE
Support Puppeteer 1.5

### ISSUE THREAD

**Issue by felixfbecker** [joelgriffith/browserless#22]
With Puppeteer 1.5 connecting fails with:
```
     Error: Protocol error (Target.getBrowserContexts): 'Target.getBrowserContexts' wasn't found undefined
      at Promise (node_modules/puppeteer/lib/Connection.js:86:56)
  From previous event:
      at Connection.send (node_modules/puppeteer/lib/Connection.js:85:12)
      at Function.connect (node_modules/puppeteer/lib/Launcher.js:257:50)
      at <anonymous>
```

**Comment by joelgriffith** [comment]
I _just_ got an image going for 1.5.0 support, feel free to test it out (I haven’t yet checked it myself).

**Comment by joelgriffith** [comment]
1.5.0 is now supported, and available in docker (see https://hub.docker.com/r/browserless/chrome/tags/ for choices of versions). Going to close (feel free to open or comment if there's further issues, however I've been able to test without issue).

**Comment by felixfbecker** [comment]
Thanks! Seems to work!
