### ISSUE TITLE
Dynamicaly uploading files with browserWSEndpoint

### ISSUE THREAD

**Issue by Muffles** [joelgriffith/browserless#3]
Hey,
i'm trying this out as a potential service for web-testing, and one of the first tests I tried was how to handle the file upload.
When connected through puppeteer with browserWSEndpoint, I just can't seem to upload files dynamicaly, while without the browserWSEndpoint, it works fine.
I've even tried passing down the headers `--allow-file-access-from-files&--disable-web-security` but without any luck.

Here's how i'm trying:
```javascript
const browser = await puppeteer.connect({
    browserWSEndpoint: 'ws://localhost:32769',
    headless: true
})
const page = await browser.newPage();
await page.goto('http://localhost:8080', {waitUntil: 'networkidle2'});

(...)

let testUpload = async () => {
    const upload = await page.$("input");
    await upload.uploadFile('test.jpg');
    await page.screenshot({path: 'test_s_'+Date.now()+'.png'});
}

(...)
```

I'm 100% sure that all the elements exist, being the DOM elements or the files.
Any ideas or is this a limitation?

Cheers

**Comment by joelgriffith** [comment]
I'm guessing this might be trickier since it's interacting with a docker image, so I'm not entirely sure how uploads should function there.

Have you tried using the debugger to see if it works to the point where the upload input is there?

**Comment by pklingem** [comment]
having the same problem here.  Continuing it investigate, will report back if we find a resolution.

**Comment by joelgriffith** [comment]
Thanks @pklingem, I'd be very curious to hear how it's functioning!

**Comment by joelgriffith** [comment]
@Muffles I'll address this in documentation, but it looks like in order to have the upload functionality working you'll need to have a volume mounted with the files present (since Chrome expects the file to be on the same FS).

See Patrick's comment and linked issue since it goes into depth on how to resolve!
