### ISSUE TITLE
Debugging connection was closed. Reason: WebSocket disconnected

### ISSUE THREAD

**Issue by angelom88** [joelgriffith/browserless#32]
I have followed the straightforward instructions from docker and was doing proxy via nginx, also configured the ssl as well via certbot. But it says debugging connection was closed. Below was the url I am trying to achieve.

https://browserless.ngelmat.me

**Comment by joelgriffith** [comment]
```shell.js:3470 WebSocket connection to 'wss://browserless.ngelmat.me/debugger/module.exports%20%3D%20async%20(%7B%20page%20%7D)%20%3D%3E%20%7B%0A%20%20await%20page.goto(%27https%3A%2F%2Fexample.com%27)%3B%0A%7D%3B%0A%20%20%20%20%20%20' failed: Error during WebSocket handshake: Unexpected response code: 404```

Is nginx not able to route to this path (this is the debugger path for injecting scripts to run). Since this uses websockets the nginx proxy has to have a little more added to it. Below is an example that the hosted-service uses:

```  location / {
    proxy_pass YOUR_DOCKER_IMAGE_LOCATION;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection 'upgrade';
    proxy_set_header Host $host;
    proxy_cache_bypass $http_upgrade;
    proxy_connect_timeout       900;
    proxy_send_timeout          900;
    proxy_read_timeout          900;
    send_timeout                900;
  }```

**Comment by angelom88** [comment]
Works great now @joelgriffith . Many thanks! ^^)

**Comment by joelgriffith** [comment]
FWIW added to the main README: https://github.com/joelgriffith/browserless#recommended-nginx-config
