### ISSUE TITLE
Implement option to set server host

### ISSUE THREAD

**Issue by Filipoliko** [joelgriffith/browserless#33]
I encountered an issue in our gitlab-ci pipeline, that sometimes connection reset error occured when two or more docker containers communicate with each other. I found out, that to solve this issue, I should set the server host to bind to IP 0.0.0.0. I updated the IP address and it seems to be working without any issue now. We created our own image with this change, but it would be great, to have this also integrated in the official repo.

**Comment by joelgriffith** [comment]
PR is merged, going to close (thanks again)
