### ISSUE TITLE
Timeout issues ?

### ISSUE THREAD

**Issue by skwidy** [joelgriffith/browserless#37]
I'm wondering, would there be any timeout issues using this technique ?
For example if I'd launch a big crawl for +24 hours

I'd say no, but maybe you pushed it to its limits :)

Thanks

**Comment by skwidy** [comment]
You got it right :) 
Ok, that's not too much actually, it'd be like 20$/mo on DigitalOcean for a single container to get it running every day of the month 

But I guess it'd be better to restrict the execution time to something like 5 to 6 hours ...

**Comment by joelgriffith** [comment]
You can also set the CONNECTION_TIMEOUT Parma to -1, which will trigger it _not_ to ever close the browser automatically. This is great for cases where you manage the chrome pool in your app and never run more than the concurrency limit set.

This is a relatively new feature, so double check eeverythingr before using it!

**Comment by joelgriffith** [comment]
Going to close this issue as we aren’t actively working on a fix. Feel free to keep the discussion going however.
