### ISSUE TITLE
MaxListenersExceededWarning if MAX_CONCURRENT_SESSION>10 and PREBOOT_CHROME=true

### ISSUE THREAD

**Issue by panthony** [joelgriffith/browserless#38]
If you use PREBOOT_CHROME & MAX_CONCURRENT_SESSION > 10 then you get a MaxListenersExceededWarning for a bunch of events:

```
% docker run -e "PREBOOT_CHROME=true" -e "MAX_CONCURRENT_SESSIONS=11" -p 3000:3000 browserless/chrome:latest
(node:27) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 exit listeners added. Use emitter.setMaxListeners() to increase limit
(node:27) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 SIGINT listeners added. Use emitter.setMaxListeners() to increase limit
(node:27) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 SIGTERM listeners added. Use emitter.setMaxListeners() to increase limit
(node:27) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 SIGHUP listeners added. Use emitter.setMaxListeners() to increase limit
```

From Node documentation:

> By default EventEmitters will print a warning if more than 10 listeners are added for a particular event. 

Maybe browserless should increase the [max listener allowed](https://nodejs.org/docs/latest/api/events.html#events_emitter_setmaxlisteners_n) to the `MAX_CONCURRENT_SESSION` ?

**Comment by joelgriffith** [comment]
Great find, I'll work towards a fix this weekend. That being said, this is mostly just a warning, so I wouldn't worry _too_ much about it at this point.

**Comment by joelgriffith** [comment]
@panthony this should now be fixed in `master` and `release-*` branches (as well as in docker once the builds complete).  Let me know if you run into further issues.
