### ISSUE TITLE
How to configure a proxy?

### ISSUE THREAD

**Issue by gajus** [joelgriffith/browserless#4]
Is there a way to configure a proxy used by Chrome to make all the HTTP requests?

**Comment by joelgriffith** [comment]
Yes: you should be able to use the proxy CLI flags ([which browserless exposes via query-string parameters](https://docs.browserless.io/configuration/parameters/)). After that, in your script use [puppeteer's  method](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pageauthenticatecredentials) to provide credentials.

**Comment by joelgriffith** [comment]
Going to close this -- feel free to actively discuss or join us on Slack: https://join.slack.com/t/browserless/shared_invite/enQtMzA3OTMwNjA3MzY1LWMzMThjZTdkNzM5NDgwYTgwYzg0YzRhMGFhZGViYjQ4MzgyYWMxNDc0OTgyYzE0ZWFkOGQ2MjI4Yzk3MmQzNTk
