### ISSUE TITLE
Repo should link to additional docs

### ISSUE THREAD

**Issue by shawnmaten** [joelgriffith/browserless#55]
You have other documentation on https://docs.browserless.io but you don't point that out in the README or anywhere else in the repo. I was having an issue with the debugger session disconnecting and was digging into whether it was in issue with my proxy server but it turns out all I needed was to know about the `CONNECTION_TIMEOUT` env variable mentioned [here](https://docs.browserless.io/docs/docker.html). So I think it would make sense to specifically call out the additional documentation somewhere obvious such as the README or maybe to combine all the docs for the open source project and separate them from the service docs.

I also just want add a 👏👏 great job on the project. I've been trying to get something setup with puppeteer and headless chrome for awhile and this is super useful and much appreciated. And the web debugger is 🔥😍.

**Comment by joelgriffith** [comment]
Fixed in https://github.com/joelgriffith/browserless/pull/56
