### ISSUE TITLE
Japanese fonts

### ISSUE THREAD

**Issue by luminous8** [joelgriffith/browserless#58]
Hi,

When I made a screenshot of this website http://fshr-kyoto.com, fonts are missing.
Any idea how to display them?

![790e7yofl176tdaeysms2bfqyu6ebvvarmjl3h9b7dne](https://user-images.githubusercontent.com/17875165/45404473-66f0b700-b65f-11e8-8fcd-640fb51ac653.jpg)

**Comment by joelgriffith** [comment]
Interesting, they work at https://chrome.browserless.io/?script=await%20page.goto(%27http%3A%2F%2Ffshr-kyoto.com%2F%27)%3B. Are you doing PDF's or otherwise?

**Comment by luminous8** [comment]
Indeed that's weird as I'm doing jpg screenshot. That's weird. Do I need to install more fonts?
The server that runs chrome.browserless.io has only browserless installed on it?

**Comment by joelgriffith** [comment]
Yes, just the image. Mind pasting your code so I can repro locally?

**Comment by joelgriffith** [comment]
@luminous8 do you have any code available that we can use to repro locally? Everything thus far has been working for me, so need some guidance on narrowing down the problem

**Comment by joelgriffith** [comment]
No worries, I'll keep it open for the time being. My best guess is that something isn't being lazily loaded properly on the site, but hard to say

**Comment by luminous8** [comment]
Well, I reinstalled it on another server and it worked just fine with the same script. Not sure where it came from but it's from my side. Thanks Joel for your time!

**Comment by chaodoze** [comment]
Joel, I'm encountering similar problems with Hindi script e.g. 
curl -X POST \
  https://chrome.browserless.io/screenshot?token=<token> \
  -H 'Cache-Control: no-cache' \
  -H 'Content-Type: application/json' \
  -d '{
  "url": "https://threadreaderapp.com/thread/1060162990551584768.html",
  "options": {
    "fullPage": true,
    "type": "jpeg",
    "quality": 75
  }
}' > test.jpeg
