### ISSUE TITLE
Puppeteer v1.8.0

### ISSUE THREAD

**Issue by glennjones** [joelgriffith/browserless#63]
There is an issue "ignoreHTTPSErrors is not working when request interception is on" which is fixed with puppeteer v1.8.0. Can you move the project onto the latest version, Thanks Glenn

https://github.com/GoogleChrome/puppeteer/issues/1159#issuecomment-418296568

**Comment by joelgriffith** [comment]
Hey there!

We’ve actually got 1.8.0 on master (and I’ve checked the lock file as well). Plus there’s a docker build as well here for 1.8.0. I’d be curious to hear which one isn’t working properly so I can see why. Some sample code would be good too

Thanks!

**Comment by joelgriffith** [comment]
Hrm, looks like this is an issue in Chrome Linux even on latest puppeteer: https://bugs.chromium.org/p/chromium/issues/detail?id=877075

**Comment by glennjones** [comment]
Hi Joel, This may have been a bit of a none issue, we got it working. Thanks for the reply I will close this down
