### ISSUE TITLE
Support for Cookies Object?

### ISSUE THREAD

**Issue by xpose2000** [joelgriffith/browserless#67]
I emailed earlier but wanted to create an official issue about adding support for cookies in Chrome. This could be accomplished by passing a cookies object.

Let me know if you have follow up questions.

**Comment by xpose2000** [comment]
Yes, that looks like it should do the trick. Excited to give it a try :) Amazing for implementing this so quickly

**Comment by joelgriffith** [comment]
Going to close this out then and start updating the release branches

**Comment by joelgriffith** [comment]
https://hub.docker.com/r/browserless/chrome/builds/

Once these are done, you should be good to go!
