### ISSUE TITLE
Browserless proxy terminates session in response to cookie DELETE request

### ISSUE THREAD

**Issue by outerim** [joelgriffith/browserless#77]
I've been trying to get capybara working with browserless in a rails app using selenium. During the test cycle capybara will [tell the selenium driver to reset cookies](https://github.com/teamcapybara/capybara/blob/e320f5d7fc43357fbc8b9d4895fb3b457c996758/lib/capybara/selenium/driver.rb#L127). Selenium uses a DELETE request to /session/XXXXXXXXXX/cookie to handle this. It appears that browserless's proxy somewhat naively treats all DELETE requests by [closing the session](https://github.com/joelgriffith/browserless/blob/dd7e5ae7ba0ff0d0a17f2f79705e727a1aa59ff0/src/browserless-web-server.ts#L322-L331) leading to all subsequent requests from capybara/selenium to fail.

Here's a small script that demonstrates the issue:

```
require 'selenium-webdriver'
Selenium::WebDriver.logger.level = 'debug'

chrome_options = Selenium::WebDriver::Remote::Capabilities.chrome(
  "chromeOptions" => { args: %w( --headless --no-sandbox --disable-gpu ) }
)

s = Selenium::WebDriver::Remote::Driver.new(desired_capabilities: chrome_options, url: "http://chrome:4444/webdriver")

s.manage.delete_all_cookies
s.navigate.to('about:blank') # Will fail
```

It seems from the documentation that there are a [handful of DELETE requests in the spec](https://github.com/SeleniumHQ/selenium/wiki/JsonWireProtocol#command-reference). I. think the appropriate thing to do is to only close the session when encountering a DELETE to the /session/ID url.

I'm gonna mess around with a PR for this but feel free to comment in the mean time if you have encountered this and feel like my approach is ill advised for some reason.

**Comment by joelgriffith** [comment]
Closing this since your PR addressed it
