### ISSUE TITLE
Chinese characters do not render properly: missing system fallback font (?)

### ISSUE THREAD

**Issue by dbertram** [joelgriffith/browserless#8]
Repro steps:

- Render a page containing some Chinese characters such as the following: `中文樣本文本`
- Load page with browserless + capture as pdf or png

Expected: Characters rendered correctly in output

Actual: Chinese characters rendered as missing glyph "box"

**Comment by dbertram** [comment]
Some initial scouting re: default fallback system fonts for `sans-serif`:

- On Windows: `SimSun`
- On Mac OS X: `PingFang SC`
- On Fedora 27: `Source Han Sans CN Regular`

Some additional info here http://www.kendraschaefer.com/2012/06/chinese-standard-web-fonts-the-ultimate-guide-to-css-font-family-declarations-for-web-design-in-simplified-chinese/

There also appear to be some early access Google Fonts available, namely https://fonts.google.com/earlyaccess#Noto+Sans+SC and https://fonts.google.com/earlyaccess#Noto+Sans+TC

**Comment by joelgriffith** [comment]
Got a build going here: https://hub.docker.com/r/browserless/chrome/builds/b9pserg8tdaglnkr2a6njlk/ might want to check that out once it's complete

**Comment by joelgriffith** [comment]
Using https://chrome.browserless.io/?script=await%20page.goto(%27https%3A%2F%2Fgithub.com%2Fjoelgriffith%2Fbrowserless%2Fissues%2F8%27)%3B as a reference point (yes, loading _this_ page with the characters mentioned) indicates that this isn't an issue any longer.

Going forward we'll probably be using more of Noto's fonts (right now just CJK) to make sure all fonts are present.

**Comment by dbertram** [comment]
@joelgriffith I think we're ok to close this out. The updated font stack you added appears to work for the Chinese/Japanese/Korean issues we were running into. Thanks for resolving this for us!
