### ISSUE TITLE
Question: How to upload files

### ISSUE THREAD

**Issue by Publish-Interactive** [joelgriffith/browserless#91]
First I'd like to say this looks like a fantastic product, I'm evaluating whether to move from C# Selenium to JS Puppeteer / browserless.

We have a lot of tests which upload files, and I'm not sure how to go about uploading a file through browserless.

I have this demo code which runs in the debug window:

    module.exports = async ({ page }) => {
      await page.goto('http://host.docker.internal:8123/user');
      const input = await page.$('[name=imagefile]') 
      await input.uploadFile("/c/dev/test.png")
      await page.click("#submit-button")
    };

Everything works up until I the submit-button click. It loads a blank page and if I preserve the network log, it shows the request failed:

![image](https://user-images.githubusercontent.com/29606496/48422783-4922f980-e757-11e8-97bb-5be7489377ab.png)

Obviously I took a complete guess at the file location! It's currently on my base windows image at C:\dev\test.png and the usual linux conversion for mounted drives would be /c/dev/test.png.

Does browserless support uploading files? Is there a way to upload the file into the same docker machine that the browser is running in?

**Comment by joelgriffith** [comment]
Yes! You have to launch Chrome with a path to where downloads should be. You can do this in a browserless container with our launch flags (documented on our site).

Once that’s done the file should be there for you to do whatever with. Again, in docker, I’d have the host mount a volume for the docker container to use as a path for downloads. We definitely could use docs on this, and I’ll look at adding some soon

**Comment by joelgriffith** [comment]
https://github.com/joelgriffith/browserless/pull/116/files#diff-96558821c734911dbda7678786864230R117 Addressess this by allowing users to upload files into a "workspace" area. Ideally this location is ephemeral, as browserless _doesn't_ do any sort of cleanup or disposal of files on the machine. By default it'll mount a temporary directory, via os.tmpdir(), as the folder to allow uploads.

Doing a GET on `/workspace` will list out files and some file-stats, while a GET on `/workspace/${file}` downloads it. Finally, when uploading files, the service responds with an array (always) of files uploaded + details about them.

More coming in docs about this!

**Comment by joelgriffith** [comment]
:boom: https://docs.browserless.io/docs/workspace.html now has docs on how to upload files into browserless for inputing into a website
