### ISSUE TITLE
How to pass launch options? 

### ISSUE THREAD

**Issue by obaid** [joelgriffith/browserless#94]
I can see from the documentation that we can use `--` to pass launch options, but I am trying to find out how to pass `ignoreDefaultArgs` options?

This is what my options looks like right now launching locally:

```
var options     = {
  headless: false,
  args: [
    '--enable-usermedia-screen-capturing',
    '--allow-http-screen-capture',
    '--disable-infobars',
    `--window-size=${width},${height}`,
  ],
  ignoreDefaultArgs: ['--mute-audio']
}```

**Comment by joelgriffith** [comment]
Yup, not currently possible, but definitely something I'm going to add shortly. This plus the `headless` and a few others will likely make the first cut.

**Comment by obaid** [comment]
Awesome! Looking forward to it.

**Comment by joelgriffith** [comment]
Should be addressed in https://github.com/joelgriffith/browserless/pull/96. Docs landing soon

**Comment by joelgriffith** [comment]
https://docs.browserless.io/docs/chrome-flags.html#ignoring-default-flags let me know if this works -- browserless does log the launch options when `DEBUG=browserless*`!

**Comment by obaid** [comment]
Thanks, @joelgriffith. I will try it out shortly.

**Comment by conradkdotcom** [comment]
@joelgriffith Thanks for implementing that ! Very useful in development for us :+1:

**Comment by joelgriffith** [comment]
Great! I’m going to close this then for the time being. If something comes up we can dive into it further via another issue.
