### ISSUE TITLE
MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 21 SIGHUP listeners added. Use emitter.setMaxListeners() to increase limit

### ISSUE THREAD

**Issue by nloui** [joelgriffith/browserless#97]
Hey there, I'm getting this error pretty often in my logs:

(node:18) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 21 SIGHUP listeners added. Use emitter.setMaxListeners() to increase limit

with these ENV settings:

PREBOOT_CHROME | true
MAX_QUEUE_LENGTH | 10
MAX_CONCURRENT_SESSIONS | 20
ENABLE_DEBUGGER | false
ENABLE_CORS | true

I noticed issue #38 reference a similar problem, but it looks like it should have been resolved.

**Comment by joelgriffith** [comment]
Should be fixed now in latest push, let me know if not!
